# --- use newest yt-dlp and not the one debian apt supplies
script-opts-append=ytdl_hook-ytdl_path=/usr/local/bin/yt-dlp

# --- ytdlp options
ytdl-format=bestvideo+bestaudio/best
#ytdl-format=bestvideo[height<=?1080][vcodec^=avc]+bestaudio/best # nouveau too slow

# --- graphix
vo=gpu-next
gpu-api=vulkan
hwdec=nvdev-copy
video-sync=display-resample
interpolation=yes
tscale=oversample
profile=high-quality
cscale=ewa_lanczossharp

# --- streaming
cache=yes
demuxer-max-bytes=1000MiB
demuxer-max-back-bytes=500MiB

# --- qol
stop-screensaver=yes
save-position-on-quit=yes
keep-open=yes
player-operation-mode=cplayer

